/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AudioMessage = IDL.Record({
  'audioData' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : IDL.Nat,
});
export const Stroke = IDL.Record({
  'color' : IDL.Text,
  'thickness' : IDL.Float64,
  'points' : IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64)),
});

export const idlService = IDL.Service({
  'addAudioMessage' : IDL.Func([IDL.Text, AudioMessage], [], []),
  'addStroke' : IDL.Func([IDL.Text, Stroke], [], []),
  'createRoom' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllRoomCodes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAudioMessages' : IDL.Func([IDL.Text], [IDL.Vec(AudioMessage)], ['query']),
  'getStrokes' : IDL.Func([IDL.Text], [IDL.Vec(Stroke)], ['query']),
  'joinRoom' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AudioMessage = IDL.Record({
    'audioData' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : IDL.Nat,
  });
  const Stroke = IDL.Record({
    'color' : IDL.Text,
    'thickness' : IDL.Float64,
    'points' : IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64)),
  });
  
  return IDL.Service({
    'addAudioMessage' : IDL.Func([IDL.Text, AudioMessage], [], []),
    'addStroke' : IDL.Func([IDL.Text, Stroke], [], []),
    'createRoom' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllRoomCodes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAudioMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AudioMessage)],
        ['query'],
      ),
    'getStrokes' : IDL.Func([IDL.Text], [IDL.Vec(Stroke)], ['query']),
    'joinRoom' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };