/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'createPairingCode' : IDL.Func([IDL.Text], [], []),
  'getAllPairingCodes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'pollMessage' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'registerRecipient' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'createPairingCode' : IDL.Func([IDL.Text], [], []),
    'getAllPairingCodes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'pollMessage' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'registerRecipient' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };